INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (1, 'posDesc1', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (6, 'posDesc2', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (11, 'posDesc3', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (16, 'posDesc4', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (21, 'posDesc5', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (26, 'posDesc6', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (31, 'posDesc7', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (36, 'posDesc8', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (41, 'posDesc9', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (46, 'posDesc10', true, '');

INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (2, 'posAns1', true, 1, 1);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (3, 'posAns2', false, 1, 1);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (4, 'posAns3', false, 1, 1);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (5, 'posAns4', false, 1, 1);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (7, 'posAns1', true, 1, 6);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (8, 'posAns2', false, 1, 6);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (9, 'posAns3', false, 1, 6);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (10, 'posAns4', false, 1, 6);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (12, 'posAns1', true, 1, 11);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (13, 'posAns2', false, 1, 11);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (14, 'posAns3', false, 1, 11);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (15, 'posAns4', false, 1, 11);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (17, 'posAns1', true, 1, 16);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (18, 'posAns2', false, 1, 16);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (19, 'posAns3', false, 1, 16);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (20, 'posAns4', false, 1, 16);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (22, 'posAns1', true, 1, 21);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (23, 'posAns2', false, 1, 21);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (24, 'posAns3', false, 1, 21);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (25, 'posAns4', false, 1, 21);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (27, 'posAns1', true, 1, 26);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (28, 'posAns2', false, 1, 26);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (29, 'posAns3', false, 1, 26);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (30, 'posAns4', false, 1, 26);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (32, 'posAns1', true, 1, 31);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (33, 'posAns2', false, 1, 31);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (34, 'posAns3', false, 1, 31);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (35, 'posAns4', false, 1, 31);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (37, 'posAns1', true, 1, 36);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (38, 'posAns2', false, 1, 36);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (39, 'posAns3', false, 1, 36);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (40, 'posAns4', false, 1, 36);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (42, 'posAns1', true, 1, 41);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (43, 'posAns2', false, 1, 41);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (44, 'posAns3', false, 1, 41);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (45, 'posAns4', false, 1, 41);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (47, 'posAns1', true, 1, 46);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (48, 'posAns2', false, 1, 46);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (49, 'posAns3', false, 1, 46);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (50, 'posAns4', false, 1, 46);