INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (51, 'negDesc1', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (56, 'negDesc2', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (61, 'negDesc3', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (66, 'negDesc4', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (71, 'negDesc5', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (76, 'negDesc6', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (81, 'negDesc7', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (86, 'negDesc8', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (91, 'negDesc9', true, '');
INSERT INTO public.question (id, description, is_multiple_choice, picture_path) VALUES (96, 'negDesc10', true, '');

INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (52, 'negAns1', true, 1, 51);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (53, 'negAns2', false, -1, 51);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (54, 'negAns3', false, -1, 51);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (55, 'negAns4', false, -1, 51);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (57, 'negAns1', true, 1, 56);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (58, 'negAns2', false, -1, 56);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (59, 'negAns3', false, -1, 56);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (60, 'negAns4', false, -1, 56);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (62, 'negAns1', true, 1, 61);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (63, 'negAns2', false, -1, 61);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (64, 'negAns3', false, -1, 61);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (65, 'negAns4', false, -1, 61);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (67, 'negAns1', true, 1, 66);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (68, 'negAns2', false, -1, 66);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (69, 'negAns3', false, -1, 66);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (70, 'negAns4', false, -1, 66);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (72, 'negAns1', true, 1, 71);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (73, 'negAns2', false, -1, 71);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (74, 'negAns3', false, -1, 71);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (75, 'negAns4', false, -1, 71);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (77, 'negAns1', true, 1, 76);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (78, 'negAns2', false, -1, 76);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (79, 'negAns3', false, -1, 76);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (80, 'negAns4', false, -1, 76);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (82, 'negAns1', true, 1, 81);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (83, 'negAns2', false, -1, 81);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (84, 'negAns3', false, -1, 81);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (85, 'negAns4', false, -1, 81);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (87, 'negAns1', true, 1, 86);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (88, 'negAns2', false, -1, 86);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (89, 'negAns3', false, -1, 86);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (90, 'negAns4', false, -1, 86);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (92, 'negAns1', true, 1, 91);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (93, 'negAns2', false, -1, 91);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (94, 'negAns3', false, -1, 91);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (95, 'negAns4', false, -1, 91);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (97, 'negAns1', true, 1, 96);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (98, 'negAns2', false, -1, 96);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (99, 'negAns3', false, -1, 96);
INSERT INTO public.answer (id, description, is_correct_answer, points, question_id) VALUES (100, 'negAns4', false, -1, 96);

